### ISSUE TITLE
Read.Me Update

### ISSUE THREAD

**Issue by meowserkat** [zeropingheroes/lanager#104]
In Ubutbtu 16.04 some of the apt-get packages have changed or are no longer available in the new version. Can the installation instructions be updated? Or is it recommended to still use 14.04?

**Comment by ilumos** [comment]
14.04 is still supported until April 2019 so its fine to use. If you prefer to use 16.04 and you'd like to submit a pull request for an edited readme with instructions I'll accept it :)
