### ISSUE TITLE
No image on games, looks like url is not working anymore

### ISSUE THREAD

**Issue by eivl** [zeropingheroes/lanager#105]
the url looks like this : 

http://cdn.steampowered.com/v/gfx/apps/245170/capsule_184x69.jpg

it seems like this is not working anymore

a link that looks like to be working is this one : 
http://cdn.edgecast.steamstatic.com/steam/apps/245170/capsule_184x69.jpg

i got that one from the product page on steam, but i know nothing about if this is correct or not.

**Comment by cruelviper** [comment]
yes, it is right, i made a dirty solution, go to:
`/vendor/tsukanov/steam-locomotive/src/Tsukanov/SteamLocomotive/Core/Tools/Store.php`

and change every entry for:
`http://cdn.steampowered.com/v/gfx/apps/`
to
`http://cdn.akamai.steamstatic.com/steam/apps/`


that is all. if it does not work, please delete  every folder in the folder:
> /app/storage/cache/
and delete every file in the Folder:
> /app/storage/views/
this shut clean up cached files.

**Comment by ilumos** [comment]
Yes, the upstream library is out of date and needs to be fixed.

**Comment by VibroAxe** [comment]
Upstream has now been updated https://github.com/gentlecat/steam-locomotive/issues/14#event-1098135826
