### ISSUE TITLE
ERROR: Could not find text 'installed' 

### ISSUE THREAD

**Issue by meowserkat** [zeropingheroes/lanager#108]
2017-10-19 14:29:09 ERROR: Could not find text "'installed'     => false" in "app/config/lanager/config.php"
2017-10-19 14:29:09 INSTALLATION ABORTED
2017-10-19 14:29:09 Raise an issue on GitHub

backstory: I had some issues downloading php, started from scratch and downloaded everything before updating the repositories.  composer would not download, found an alternate way to download it with curl. 

Issue: Got everything going and did the install.  Right at the end I got the above error. I looked at the file and the line is there, so I am not sure why it could not find it?  However,  I tested the app and it seems to be working. I was able to login with a steam account and browse around. I went back and manually changed the installed = false to   installed = true.

**Comment by ilumos** [comment]
Yes I've also experienced this - a small change is needed to fix this. Thank you for creating the issue!

**Comment by ilumos** [comment]
The new version of LANager that I'm working on uses `env` files for configuration, instead of the clunky install process.
