### ISSUE TITLE
Install Lanager

### ISSUE THREAD

**Issue by Yogi85** [zeropingheroes/lanager#109]
Hello
I want to create such a server. But unfortunately I can not install PHP5. Can someone help me. I'm not that good with Linux.

Thank you

Gruess Yogi

**Comment by klitztuch** [comment]
For help something like an error-message is needed. What is the problem when you install php5?

**Comment by ilumos** [comment]
Hi folks,

The new version of LANager currently in development will use PHP 7. Until then you can install PHP 5 on Ubuntu Server by following instructions here:

https://askubuntu.com/questions/756181/installing-php-5-6-on-xenial-16-04

Thanks!
