### ISSUE TITLE
How do you edit or modify links?

### ISSUE THREAD

**Issue by DeusMaximus** [zeropingheroes/lanager#110]
Sorry if I'm missing something obvious, but I cannot for the life of me figure out how to edit the links. I've been trying to dig through the code and figure out how it displays them, and where it pulls them from.

Do I have to edit the database by hand?

**Comment by ilumos** [comment]
Hey there! Edit this file: `app/config/lanager/links.php`

https://github.com/zeropingheroes/lanager/blob/master/app/config/lanager/links.php

Enjoy :)
