### ISSUE TITLE
Error 500 - Signup for non-admin users

### ISSUE THREAD

**Issue by kaylabs** [zeropingheroes/lanager#112]
Hi, i have pulled your master-branch and created an event - The people can't signup if they don't have admin role.

-----

OT: Btw where can i edit the links in the link section?,
Where to find the "Servers" and "Playlist" Tab ? 

Kind regards

Kaylabs

**Comment by ilumos** [comment]
Hey, I've heard this signup issue before and will look into it shortly. 

In this version it's not possible to edit those links.

Thanks!

**Comment by ilumos** [comment]
The 500 error should now be fixed now that this pull request is merged:

https://github.com/zeropingheroes/lanager/pull/101
