### ISSUE TITLE
Docs for schema?

### ISSUE THREAD

**Issue by msmollin** [zeropingheroes/lanager#114]
Currently have a homemade PHP lan management system that's like over 10 years old that I wanna replace. I have a bunch of historical data though in there that i'd like to migrate over. Is there any docs on the schema that lanager uses so I can see about writing a migration script?

Thanks!

**Comment by ilumos** [comment]
Hi Matt,

These files will give you an idea:

https://github.com/zeropingheroes/lanager/tree/laravel-upgrade/database/migrations

If you would like to see in native SQL, download/git clone the project, run `vagrant up` and then examine the database's schema by connecting to MySQL on localhost:33060

I hope this helps! :)
