### ISSUE TITLE
Trying to get property 'type' of non-object

### ISSUE THREAD

**Issue by shivshankar456** [zeropingheroes/lanager#116]
![screenshot from 2018-12-19 23-26-40](https://user-images.githubusercontent.com/3935378/50239944-89763700-03e9-11e9-82d8-f1da3b660e22.png)
![screenshot from 2018-12-19 23-27-39](https://user-images.githubusercontent.com/3935378/50239950-89763700-03e9-11e9-9c46-1a529eac626c.png)
![screenshot from 2018-12-19 23-28-08](https://user-images.githubusercontent.com/3935378/50239951-8a0ecd80-03e9-11e9-902c-c849e0cda2b0.png)

**Comment by ilumos** [comment]
Hi there, that's not my code 😂 

Tried to find whose project that is for you but couldn't, sorry!
