### ISSUE TITLE
mysql problem? 

### ISSUE THREAD

**Issue by remorsan** [zeropingheroes/lanager#125]
Im getting this on the url, and dont really know how to resolve it.
The debug file is empty and as far as i can understand, the permissions are correct.

> Unable to update data for user remorsan - SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`lanager`.`steam_user_metadata`, CONSTRAINT `steam_user_metadata_steam_user_status_code_id_foreign` FOREIGN KEY (`steam_user_status_code_id`) REFERENCES `steam_user_status_codes` (`id`) ON DEL) (SQL: insert into `steam_user_metadata` (`user_id`, `steam_user_status_code_id`, `profile_visible`, `profile_updated_at`) values (2, 4, 1, 2019-08-22 11:53:11))

> 

Kind regards

**Comment by ilumos** [comment]
Hey there, can you run this from the project's root directory:
```bash
php artisan db:seed
```
and see if the error persists

**Comment by remorsan** [comment]
Thanks, that did the trick for me. :-)
