### ISSUE TITLE
Can't use Steam OpenID login, throwing "error" with no reason from Steam

### ISSUE THREAD

**Issue by DrumSlayers** [zeropingheroes/lanager#127]
Hello,
We are trying to setup Lanager for a LAN Party, the panel itself work, but when we try to log in via steam, the steam website is throwing a simple "error" with no reason, after clicking connect button
![image](https://user-images.githubusercontent.com/4050278/66708054-cfbacf00-ed4a-11e9-9342-3e5f10320cf2.png)
We searched on web and on closed issues, but we didn't found anything.
Can you help us resolve the problem? We saw things related to website not being in SSL, but your guide for installation if in HTTP so we don't understand.

Thank you.

**Comment by DrumSlayers** [comment]
No answer for this?

**Comment by ilumos** [comment]
Can you paste the contents of your `.env` file, removing API keys and other secrets?

Can you also paste the Steam URL that gives the error?

**Comment by avelinnt** [comment]
`APP_NAME=LANager
APP_ENV=production
APP_KEY=*********************************
APP_DEBUG=false
APP_URL=intra.airthelan.party
APP_TIMEZONE=UTC

STEAM_API_KEY=*********************************
GOOGLE_API_KEY=*********************************

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=lanager
DB_USERNAME=********
DB_PASSWORD=*****************

CACHE_DRIVER=file
SESSION_DRIVER=database
SESSION_LIFETIME=7200
LOG_CHANNEL=stack`

The following URL gives us the "Error":
https://steamcommunity.com/openid/login
![image](https://user-images.githubusercontent.com/23199733/67700673-acc92580-f9ae-11e9-87a3-a65deef1481b.png)

**Comment by ilumos** [comment]
Can you paste the entire URL, with query string please :)

Also try adding http:// to your APP_URL - that may fix it

>

**Comment by DrumSlayers** [comment]
Hello, thank for reply!
Avelinnt gave the Full request URL after pressing the "Connect with steam" button on manager
(https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=intra.airthelan.party%2Fauth%2Fsteam%2Fcallback&openid.realm=http%3A%2F%2Fintra.airthelan.party&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select)

We will try to add http(s):// as you say (we use tls) :)

Don't the fact that our Lanager isn't accessible on internet a problem? We already have a tool that worked with steam connection on local, but maybe Lanager's system is different?

Thank you

**Comment by ilumos** [comment]
Great thank you. Yes do try with http and let me know if that works

It will not matter that your install is not accessible on the internet - I
have tested this many times while developing locally.

Good luck :)

**Comment by avelinnt** [comment]
Okay so as you advised, we added http:// before our URL and it works! 👍 

We're now able to manage our LAN party.
Thanks again! :)

**Comment by ilumos** [comment]
That's great news :)

**Comment by vexyyv** [comment]
im having the same issue if at all possible could you help me

**Comment by ehbstudentadam** [comment]
Had the same problem. This fixed it for me (windows):
.env file -> APP_URL=http://xxx.party:8080
STEAM_API_KEY -> request one with domain: http://xxx.party
local hosts file: 127.0.0.1 xxx.party
