### ISSUE TITLE
Date Field Format Error

### ISSUE THREAD

**Issue by meowserkat** [zeropingheroes/lanager#128]
Error in date field when creating LAN event. 
When entering dates. Calendar pops up and gives format of:  MM-DD-YYYY HH:MM:SS

But when submitting page gives error: "does not match the format Y-m-d H:i:s"

![lanager_schedule_error](https://user-images.githubusercontent.com/13814749/69488688-86be6600-0e32-11ea-8b18-7fdcd96448f0.jpg)

**Comment by ilumos** [comment]
The date picker should no longer use the incorrect format
