### ISSUE TITLE
SQLSTATE[22003]: Numeric value out of range: 1264

### ISSUE THREAD

**Issue by avelinnt** [zeropingheroes/lanager#130]
Greetings,

First of all, wish you a happy new year! :)

I am trying to run Lanager on my Raspberry Pi server. Unfortunately, I got an 500 error when I'm trying to log in through Steam for the first time. 
By turning `APP_DEBUG=true` I get this:

`SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'remote_addr' at row 1 (SQL: insert into `logs` (`instance`, `message`, `channel`, `level`, `level_name`, `context`, `remote_addr`, `user_agent`, `created_by`, `created_at`) values (AirThePi, Allowed memory size of 134217728 bytes exhausted (tried to allocate 12587008 bytes), production, 400, ERROR, {"exception":"Symfony\\Component\\Debug\\Exception\\FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 12587008 bytes) in \/var\/www\/lanager\/vendor\/gilg4mesh\/monolog-mysql\/src\/Logger\/Monolog\/Handler\/MysqlHandler.php:31\nStack trace:\n#0 {main}"}, -1062713853, Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0, ?, 2020-01-02 23:35:32))`

By trying to modify the memory value on php.ini, the size keeps increasing.

Kind Regards

**Comment by DrumSlayers** [comment]
Any responses out of it?
We think this is related to RPI Libs & ARM64 Libs but not sure. Same config on x86_64 server doesn't seem to throw error.
We are blocked about this as we want to host it using a RPI.

Thank you

**Comment by ilumos** [comment]
This is fixed in the `develop` branch and will be merged to master soon
