### ISSUE TITLE
  Class 'Barryvdh\Debugbar\ServiceProvider' not found

### ISSUE THREAD

**Issue by mgjuhler** [zeropingheroes/lanager#133]
Step 10: Run first-time setup commands:
```
user@lanager:/var/www/lanager$ php artisan key:generate
In Application.php line 670:
  Class 'Barryvdh\Debugbar\ServiceProvider' not found
user@lanager:/var/www/lanager$
```

**Comment by ilumos** [comment]
Good catch. For now please comment this line and the one below it:

https://github.com/zeropingheroes/lanager/blob/edd3c1fd16ec8a5dcb07dbad49f3c9c251221629/app/Providers/AppServiceProvider.php#L61
