### ISSUE TITLE
Target class [Database\\Seeders\\DatabaseSeeder] does not exist.

### ISSUE THREAD

**Issue by gugagaribaldo** [zeropingheroes/lanager#152]
Illuminate\Contracts\Container\BindingResolutionException 

  Target class [Database\\Seeders\\DatabaseSeeder] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:811

**Comment by ilumos** [comment]
Hey, please could you resubmit this using the new bug report template:

https://github.com/zeropingheroes/lanager/issues/new/choose

Thanks!
