### ISSUE TITLE
Using without Google API Key

### ISSUE THREAD

**Issue by miko007** [zeropingheroes/lanager#159]
**Describe the problem you'd like to solve**
I can not find any way to run the software without getting a Google API Key. I really do not care about the Google Maps part and i really do not want to give my credit card information to Google.

**Describe the solution you'd like**
Maybe just adding the option to leave the Google API Key empty

**Comment by mazzorini** [comment]
i could install it with the google api code "1234"

**Comment by ilumos** [comment]
I've removed the Google Maps integration as of release [v1.3.1](https://github.com/zeropingheroes/lanager/releases/tag/v1.3.1)
