### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by oksoluti** [zeropingheroes/lanager#173]
**Feature description**
Possibility to run docker container in Raspian OS

**Motivation**
I don't have an additional Linux PC available, but plenty of Raspberry Pi computers. I was about to try out  the software with one, but I think I failed because the 32-bit (armhf) Raspberry Pi OS is not supported.

The following was the output from the docker compose:

[+] Running 2/3
 ✘ lanager Error   context canceled                                                                                                                                                                                 1.9s
 ⠏ db Pulling                                                                                                                                                                                                       1.9s
 ✘ scheduler Error context canceled                                                                                                                                                                                 1.9s
no matching manifest for linux/arm/v7 in the manifest list entries

**Screenshots**
None

**Comment by ilumos** [comment]
Thanks for the feature request, and you're right, the Docker images only support the `linux/amd64` architecture.

I've had a go at creating an `linux/arm64` image, but quite a lot was broken, and I don't want to spend the time supporting another architecture, sorry :(

If you're on Windows, you can install [Docker Desktop](https://www.docker.com/products/docker-desktop/) and then follow the [LANager setup steps](https://github.com/zeropingheroes/lanager?tab=readme-ov-file#setup) to try out the project.

Hope this helps

**Comment by oksoluti** [comment]
Thanks.

Actually, just created an another issue. But I guess you already knew that one as well as you had tried out this one in the past.

Hmm...ok, quite a struggle already to get it even up and running, but it seems that I must give up :- (.
