### ISSUE TITLE
Steam Login Fails

### ISSUE THREAD

**Issue by oksoluti** [zeropingheroes/lanager#174]
**Docker image information**
I have to admit, that I'm not using an official image, as I needed to built it my self because I wanted to run lanager within my Raspberry Pi. I made the build from stable branch. Moreover, I needed to to change sql dependency from compose yml because sql 8 didn't support armv7.

But even this is the case, I recomend looking into the issue description

**Bug description**
I get following error after OAuth flow comes back to callback url.

Zeropingheroes\Lanager\Services\UpdateSteamUsersService::__construct(): Argument #1 ($steamIds) must be of type array|int, string given, called in /var/www/lanager/app/Http/Controllers/AuthController.php on line 52

This happens all the time. I haven't managed to log in successfully a single time.

I think I actually know what's the reason. Because I'm running the lanager within my Raspberry Pi,  ARMv7, which is 32 bit platform, the integer range is not capable of handling my Steam id as an integer, thus automatically converts it into a string.

**Reproduction steps**
Try to log in with your Steam account, when running lanager within Raspberry Pi / Armv7.

**Expected behavior**
User would be login successfully.

Under the hood, the steam id handling probably needs to be changed into string based, if 32 bit systems are to be supported.

**Screenshots**
None

**Comment by ilumos** [comment]
Yep you're right, Steam IDs are 64 bit integers, and when PHP runs on a 32 bit system, I think it uses strings instead, which the codebase doesn't support.

If you really want to run it on your Pi, install [Raspbian 64 bit](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/) which is supported since the Pi 2 (v1.2) :)
