### ISSUE TITLE
Allow users to sign up to events with teams

### ISSUE THREAD

**Issue by zeropingheroes** [zeropingheroes/lanager#27]
Cases:
- join, not a team event
- join, looking for a team
- join, specific team (permissions? team leader?)
- leave event and team
- leave team

**Comment by x-zempt** [comment]
This would interest me a lot to see this functionality.

**Comment by ilumos** [comment]
Abandoning this feature as the kind of events that require sign-up will likely use a 3rd party system like Challonge, which would duplicate the sign-ups.
