### ISSUE TITLE
Show user IP address on profiles

### ISSUE THREAD

**Issue by zeropingheroes** [zeropingheroes/lanager#33]
Perhaps only for admins, but can be useful for connecting to gameservers

**Comment by ilumos** [comment]
Thanks for this, will check it out on Sunday :)

**Comment by ilumos** [comment]
Had a look - it throws an exception if you are not signed in, and the styling / position on the profile is not so good. I'll merge this in in the future when I've finished refactoring the auth checks available in views. Thanks
