### ISSUE TITLE
Add seating planner

### ISSUE THREAD

**Issue by Ashbo** [zeropingheroes/lanager#38]
Could we look at getting a seating planner added? ie, when a user buys ticket (Maybe with PayPal payment complete) the user is granted access to a seat planner where a user can then pick a seat. The admin can design the seat plan in a drag and drop interface maybe? Or even with div's which have a specific class maybe such as class="seat-1" and the php script knows that assign div class seat-X to user Y?

**Comment by ilumos** [comment]
Closing as will be part of separate app dedicated to pre-event functionality (registration, payment etc)
