### ISSUE TITLE
Usage Unknown

### ISSUE THREAD

**Issue by Psychotonikum** [zeropingheroes/lanager#57]
Please update your usage section in the readme.

After 3 hours of installing we have not figured out how to add events, add game servers or add anything, except profiles through a steam login and custom links in the info section.

**Comment by ilumos** [comment]
Latest version now has basic admin dropdown for creating resources: 
![image](https://cloud.githubusercontent.com/assets/509407/7104420/10b5f270-e0d8-11e4-8197-11506d07ecee.png)

Not at alpha release yet but moving ever closer
