### ISSUE TITLE
Various ISS issues

### ISSUE THREAD

**Issue by lanops** [zeropingheroes/lanager#59]
Unsure of the problems running this on ISS, we've had several. The first being Lanager not setting "fields" to null. 

E.g.: 
SQLSTATE[HY000]: General error: 1364 Field 'pinned' doesn't have a default value (SQL: insert into `shouts` (`user_id`, `content`, `updated_at`, `created_at`) values (1, This is a test, 2015-01-12 11:49:04, 2015-01-12 11:49:04))

Specs: 
IIS - Php 5.6 mysql 5.6.21

**Comment by ilumos** [comment]
Focusing support on Ubuntu 14.04 first and foremost - don't have the resources to test cross-platform so spin up a Virtualbox VM and follow the new instructions in the readme to avoid all IIS issues
