### ISSUE TITLE
Add archive and initialise functionality for repeat events

### ISSUE THREAD

**Issue by zeropingheroes** [zeropingheroes/lanager#6]
Requested by @darabman

For recurring LAN parties using the same install of LANager, add functionality to download an archive of the previous party's data and initialise the database ready for the next party.

For each section of the database (e.g. shouts, videos, events, info etc) an admin could choose to one or both of the following:

Download an archive of the section's data
Reset the section's data to system defaults

From old Repo:

> Create a SQL script or admin page that allows authorised users to 'initialise' the database ready for a new party. Such a script should ideally perform the following actions:
> 
> Archive all shouts
> Archive non-privileged users
> Disable (but not delete) events, perhaps marking them as invisible so commonly-used events (e.g. Food orders, award ceremonies, party open/close times) can be edited and reused
> As above, but with info pages
>  Archive video playlist and initialise
> 'Archiving' would usefully have the option of either dumping CSV/SQL or outright deleting the deprecated records

**Comment by ilumos** [comment]
Delete
- logs
- event signups
- shouts
- playlist items
- playlist item votes
- states
Unpublish
- Events
- Pages
- Users

**Comment by ilumos** [comment]
Repeat events are now handled by associating events, pages and users with LANs. Only events, pages and users associated with the LAN in progress (or the most recent past LAN) is shown, but all historic data remains.
