### ISSUE TITLE
Integrate Challonge into Events.

### ISSUE THREAD

**Issue by x-zempt** [zeropingheroes/lanager#61]
Just got a couple suggestions that might be worth looking into.
If possible, when creating events, have to ability to link it to a Challonge Event so it automatically signs users up to the challonge event if they sign up to the Lanager event.
Or something along those lines.
Also have the ability to assign events to a LAN. So if you have multiple LANs setup and various events, so it makes it easier to manage etc.

**Comment by ilumos** [comment]
Yep great idea. The plan is to tie everything back to a particular LAN and be able to archive / export / hide items that were associated with older events.

**Comment by ilumos** [comment]
Closing this and tracking in duplicate issue https://github.com/zeropingheroes/lanager/issues/61

**Comment by synth3tk** [comment]
Duplicate issue is actually #34.

**Comment by ilumos** [comment]
Yeah issue control here is lackluster at best...
