### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by agreements** [zeropingheroes/lanager#62]
I get this when trying to use sudo php artisan lanager:install
changed database naturally etc.

  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lanosto.logs' do
  esn't exist (SQL: INSERT INTO logs (php_sapi_name, level, message, context,
   created_at)
                        VALUES (cli, info, [lanager:install] Testing requirements before install
  ation..., [], 2015-04-14 01:18:48))

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lanosto.logs' do
  esn't exist

**Comment by ilumos** [comment]
Yep, overlooked that logging would need to happen before database is created. Thanks for flagging this up

I'll fix this tonight - will involve conditionally disabling database logging in `app/start/global.php`

**Comment by ilumos** [comment]
Fixed in 58e0fc4d4163fdb41c0bcb8eeac7e56db4bb41ce
