### ISSUE TITLE
Allow users to propose a game to be played

### ISSUE THREAD

**Issue by ilumos** [zeropingheroes/lanager#71]

**Comment by ilumos** [comment]
Suggestion from @arianmaykon in #74 :

> Allow users to attach media to a proposed game, screenshots, videos, etc, so the others can see how the game is before vote for it

**Comment by PoxyDoxy** [comment]
I suppose this is do-able via the Shouts System, although for proper communication, a chat room would be needed to discuss the game after it has been shouted.

**Comment by ilumos** [comment]
Abandoning this feature - I expect game planning to work better in a more ad-hoc way through Discord.
