### ISSUE TITLE
Implement basic shop system

### ISSUE THREAD

**Issue by ilumos** [zeropingheroes/lanager#72]
For tuck shops, hardware, fast food orders and the like.

**Comment by x-zempt** [comment]
Keen to see this option added.
Previously we have used ALP for managing LANs, it had an addon feature that we used for pizza orders. Users would select which pizzas they wanted etc, click submit and then come and pay the admin staff. At which point the admin staff can have a export of all the orders etc to take to the pizza shop.

**Comment by ilumos** [comment]
Yes an "export orders" function would be very useful come to think of it - thanks for the tip

**Comment by ilumos** [comment]
Started work in branch [topic-shop](https://github.com/zeropingheroes/lanager/tree/topic-shop)

**Comment by ilumos** [comment]
This feature is still planned, but I'm closing all GitHub issues that aren't related to bugs, so the issue count better reflects the reliability of the software, rather than the myriad of planned features.
