### ISSUE TITLE
Create Docker image

### ISSUE THREAD

**Issue by ilumos** [zeropingheroes/lanager#75]
At time of writing LANager's installation instructions are 14 steps long, and non-trivial for users who aren't developers.

Creating a Docker image will make the LANager easier to set up, widening its appeal.

**Comment by PoxyDoxy** [comment]
I really like the Idea, I heard about docker a while back, and I think it'll greatly help spread Lanagers use.

**Comment by ilumos** [comment]
This feature is still planned, but I'm closing all GitHub issues that aren't related to bugs, so the issue count better reflects the reliability of the software, rather than the myriad of planned features.
