### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by joonax** [zeropingheroes/lanager#78]
When I open my lanager website I got error:

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Same error on every page

**Comment by ilumos** [comment]
Can you edit `app/config/app.php` and set `debug` to true, then refresh and paste the error page here

**Comment by joonax** [comment]
I took pic of it

![error](https://cloud.githubusercontent.com/assets/2136569/7820567/f4639ae0-03f1-11e5-9952-7f5b6a2bee32.png)

**Comment by ilumos** [comment]
Try running `php artisan key:generate` in your `/lanager` directory

**Comment by joonax** [comment]
Did't help. Still same error

**Comment by joonax** [comment]
I found a solution to my problem. First I ran php artisan key:generate and then copied application key and pasted it to right place in app.php file.

**Comment by ilumos** [comment]
The key:generate command should have done that for you, but good to hear you got that sorted anyway.
