### ISSUE TITLE
Allow admins to post official servers to a server list page

### ISSUE THREAD

**Issue by zeropingheroes** [zeropingheroes/lanager#8]
- Field for external server stats link
- Join link for servers including for example Mumble

**Comment by ilumos** [comment]
Decouple from Steam states as steam web API does not return LAN IPs and instead shows the public IP of the server, making join links from states unreliable

**Comment by ilumos** [comment]
With fewer and fewer games supporting dedicated servers, this feature is no longer relevant. Official servers can be listed in the info pages instead.
