### ISSUE TITLE
User achievements throws an exception if no LANs have been made

### ISSUE THREAD

**Issue by DinCahill** [zeropingheroes/lanager#80]
>ErrorException thrown with message "Undefined variable: list"
>
>Stacktrace:
>\# 23 ErrorException in [/var/www/lanager/app/start/global.php:130](https://github.com/zeropingheroes/lanager/blob/master/app/start/global.php#L130)
>\# 22 Illuminate\Exception\Handler:handleError in [/var/www/lanager/app/start/global.php:130](https://github.com/zeropingheroes/lanager/blob/master/app/start/global.php#L130)
>\# 21 lists in [/var/www/lanager/app/Http/Gui/UserAchievementsController.php:20](https://github.com/zeropingheroes/lanager/blob/master/app/Http/Gui/UserAchievementsController.php#L20)
>\<snip\>

It doesn't like an empty array of LANs.

**Comment by ilumos** [comment]
Should be fairly trivial to fix this, I'll take a look

**Comment by ilumos** [comment]
Fixed in 9d623e00dc9d65594c5db865f39c86c1d444123c
