### ISSUE TITLE
Playlists won't accept YouTube videos

### ISSUE THREAD

**Issue by TankTan38** [zeropingheroes/lanager#82]
Whenever I try to put a YouTube video into a playlist no matter the video, it says in two different red boxes: The title field is required. and The duration must be at least 1.

**Comment by ilumos** [comment]
Hi, it's most likely due to YouTube's API changes - I'll have a look this weekend

**Comment by TankTan38** [comment]
Alright, thanks.

**Comment by ilumos** [comment]
Unfortunately Google have made the video metadata API require OAuth authorisation before requests can be made. I've removed all playlist functionality for now (20f191b27ce07835a84388b768dce4eac2794656) and will introduce it back in a future version
