### ISSUE TITLE
Role Assignment Time

### ISSUE THREAD

**Issue by TankTan38** [zeropingheroes/lanager#83]
In any of the Role or User Roles pages, it says "2015 years ago" under Assigned By.

**Comment by ilumos** [comment]
Assigning a role to a user as an admin should have never done this but I did find that the first user to sign in who gets the "super admin" role assigned doesn't get the time it was assigned recorded. This is now fixed as of 265ee494fc5ab6b0e51d772180b81024f8cd34b3. Feel free to comment if this is not fixed
