### ISSUE TITLE
Pinning a Shout

### ISSUE THREAD

**Issue by TankTan38** [zeropingheroes/lanager#84]
Whenever I attempt to pin a shout, I get:

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

**Comment by ilumos** [comment]
Yeah it's all pretty broken right now... Thanks for flagging this up - I'll see how much I can sort out this weekend.

**Comment by ilumos** [comment]
Fixed in d66f1dc7b2a3004e003f8d2957badb7b506a5498
