### ISSUE TITLE
Edit LAN throws a 500 Internal Server Error

### ISSUE THREAD

**Issue by TankTan38** [zeropingheroes/lanager#85]
I have a LAN made and whenever I click Submit on its edit page, it throws a 500 Internal Server Error.

**Comment by ilumos** [comment]
Are you on the latest version? I'm working on the master branch at the moment.

If you are, what is the latest (error) log entry in http://lanager/logs

**Comment by TankTan38** [comment]
I cloned my copy of lanager on the 9th. Here's the error log:
<code>array (size=1)
  0 => string 'exception 'ErrorException' with message 'Array to string conversion' in C:\wamp\lanager\vendor\fadion\validator-assistant\src\Bindings.php:93
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(8, 'Array to string...', 'C:\\wamp\\lanager...', 93, Array)
#1 C:\wamp\lanager\vendor\fadion\validator-assistant\src\Bindings.php(93): str_ireplace(Array, Array, 'required|max:25...')
#2 [internal function]: Fadion\ValidatorAssistant\Bindings->Fadion\ValidatorAssistant\{closure}('required|max:25...', 'name')
#3 C:\wamp\lanager\vendor\fadion\validator-assistant\src\Bindings.php(94): array_walk_recursive(Array, Object(Closure))
#4 C:\wamp\lanager\vendor\fadion\validator-assistant\src\Bindings.php(28): Fadion\ValidatorAssistant\Bindings->replace(Array)
#5 C:\wamp\lanager\vendor\fadion\validator-assistant\src\ValidatorAssistant.php(428): Fadion\ValidatorAssistant\Bindings->__construct(Array, Array)
#6 C:\wamp\lanager\app\Domain\ResourceService.php(246): Fadion\ValidatorAssistant\ValidatorAssistant->bind(Array)
#7 C:\wamp\lanager\app\Domain\ResourceService.php(214): Zeropingheroes\Lanager\Domain\ResourceService->checkInputValidation('update', Array)
#8 C:\wamp\lanager\app\Domain\ResourceService.php(139): Zeropingheroes\Lanager\Domain\ResourceService->runChecks('update', Array, Array)
#9 C:\wamp\lanager\app\Http\Gui\ResourceServiceController.php(86): Zeropingheroes\Lanager\Domain\ResourceService->update('1', Array)
#10 C:\wamp\lanager\app\Http\Gui\ResourceServiceController.php(33): Zeropingheroes\Lanager\Http\Gui\ResourceServiceController->processUpdate('1', Array)
#11 [internal function]: Zeropingheroes\Lanager\Http\Gui\ResourceServiceController->update('1')
#12 C:\wamp\lanager\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#13 C:\wamp\lanager\bootstrap\compiled.php(5847): Illuminate\Routing\Controller->callAction('update', Array)
#14 C:\wamp\lanager\bootstrap\compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(Zeropingheroes\Lanager\Http\Gui\LansController), Object(Illuminate\Routing\Route), 'update')
#15 C:\wamp\lanager\bootstrap\compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Zeropingheroes\\...', 'update')
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1')
#17 C:\wamp\lanager\bootstrap\compiled.php(5398): call_user_func_array(Object(Closure), Array)
#18 C:\wamp\lanager\bootstrap\compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 C:\wamp\lanager\bootstrap\compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#20 C:\wamp\lanager\vendor\dingo\api\src\Routing\Router.php(205): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 C:\wamp\lanager\bootstrap\compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 C:\wamp\lanager\bootstrap\compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 C:\wamp\lanager\bootstrap\compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 C:\wamp\lanager\bootstrap\compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 C:\wamp\lanager\bootstrap\compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 C:\wamp\lanager\bootstrap\compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 C:\wamp\lanager\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 C:\wamp\lanager\public\index.php(49): Illuminate\Foundation\Application->run()
#29 {main}' (length=3846)</code>

**Comment by ilumos** [comment]
That error was fixed in d66f1dc7b2a3004e003f8d2957badb7b506a5498 - you can either [update to the latest version](https://github.com/zeropingheroes/lanager#updating) or edit the file manually

**Comment by TankTan38** [comment]
Alright, thank you. :)

**Comment by ilumos** [comment]
No problem :)
