### ISSUE TITLE
Use ProTube in an iframe as temporary alternative to Playlists

### ISSUE THREAD

**Issue by TankTan38** [zeropingheroes/lanager#86]
http://protu.be/ could be a good alternative to the playlists until it can be fixed, and should be easy enough to implement with an iframe or such. The generated protube link could be put into a config file or a web interface.

**Comment by ilumos** [comment]
Protube is good, but last time we used it people found it very easy to inject malicious javascript into, allowing them complete control of the video playout and other scary stuff like redirecting the user to other sites etc.

If you really want to use Protube, a link can be added in the "links" nav menu by editing `app/config/lanager/links.php`

**Comment by TankTan38** [comment]
Oh, didn't know about those security problems. I don't think anyone at my LANs knows how to do anything like that so it shouldn't be a problem for me. Thanks, will do.

**Comment by ilumos** [comment]
Yeah, this was at a university LAN full of computer science students eager to be mischevious :P
