### ISSUE TITLE
Seeding database with example data outputs the HTML source for a 500 Internal Error page

### ISSUE THREAD

**Issue by tannerkrewson** [zeropingheroes/lanager#87]
http://pastebin.com/bznHZ5w7

I've done everything following the same steps as I have before. The only difference is that I didn't reinstall wamp because I have some LAN Battlefield 3 databases in the MySQL. I tried setting installed to false in config.php and emptying the database, but the same problem happens. This is the latest lanager.

**Comment by TankTan38** [comment]
I just tried cloning at this commit, and it installs as expected and works:

https://github.com/zeropingheroes/lanager/commit/9abed318559654fb51979e59fa7c214f8bb52558

**Comment by ilumos** [comment]
I'll take a look and find out what's gone awry here. Thanks for reporting
