### ISSUE TITLE
404 on redirect from Steam login

### ISSUE THREAD

**Issue by SummitV12** [zeropingheroes/lanager#91]
I've got the system installed (working very nicely by the way). A user can navigate each page without a problem, the sign in page included; they can click sign in, they're taken to Steam, and are redirected to the wrong page after signing in.

The server resides on a local address of 10.0.0.18 (lanager shouts page is at 10.0.0.18/shouts), and on redirection the user lands at localhost/lanager..... Being that the user isn't on the server, of course it 404's.

Essentially I just need help finding what I need to change in order to rectify the Steam redirection error.

**Comment by ilumos** [comment]
Delete the contents of the `app/storage/views` and `app/storage/cache` directories and then it will regenerate the OpenID return path that is fed to Steam.

Let me know how you get on :)

**Comment by SummitV12** [comment]
Thank you so much ilumos, works like a charm!
