### ISSUE TITLE
500 Internal Server Error on Raspberry Pi 

### ISSUE THREAD

**Issue by klitztuch** [zeropingheroes/lanager#92]
After installation getting an 500 Error when trying to acces the website.

Apache Error Log:
```
[Tue Sep 29 06:25:11.706787 2015] [mpm_prefork:notice] [pid 2134] AH00163: Apache/2.4.10 (Raspbian) configured -- resuming normal operations
[Tue Sep 29 06:25:11.707007 2015] [core:notice] [pid 2134] AH00094: Command line: '/usr/sbin/apache2'
[Wed Sep 30 00:32:36.069578 2015] [:error] [pid 341] [client 192.168.0.104:44052] PHP Warning:  require(/var/www/lanager/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/lanager/bootstrap/autoload.php on line 17
[Wed Sep 30 00:32:36.069890 2015] [:error] [pid 341] [client 192.168.0.104:44052] PHP Fatal error:  require(): Failed opening required '/var/www/lanager/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/lanager/bootstrap/autoload.php on line 17
```

**Comment by ilumos** [comment]
Edit `app/config/app.php` and set `debug` to `true` then refresh and paste the error message in here.

**Comment by klitztuch** [comment]
ErrorException thrown with message "mcrypt_encrypt(): Key of size 0 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported"

Stacktrace:
#8 ErrorException in /var/www/lanager/bootstrap/compiled.php:8463
#7 Illuminate\Exception\Handler:handleError in <#unknown>:0
#6 mcrypt_encrypt in /var/www/lanager/bootstrap/compiled.php:8463
#5 Illuminate\Encryption\Encrypter:padAndMcrypt in /var/www/lanager/bootstrap/compiled.php:8456
#4 Illuminate\Encryption\Encrypter:encrypt in /var/www/lanager/bootstrap/compiled.php:8407
#3 Illuminate\Cookie\Guard:encrypt in /var/www/lanager/bootstrap/compiled.php:8379
#2 Illuminate\Cookie\Guard:handle in /var/www/lanager/bootstrap/compiled.php:11088
#1 Stack\StackedHttpKernel:handle in /var/www/lanager/bootstrap/compiled.php:657
#0 Illuminate\Foundation\Application:run in /var/www/lanager/public/index.php:49

**Comment by ilumos** [comment]
Generate a 32 character hex key and put it in the application encryption
key field in app/config/app.php

Let me know how you get on

**Comment by klitztuch** [comment]
Generated the key and it works. Thanks!
