### ISSUE TITLE
Timeout when accessing Logs as SuperAdmin

### ISSUE THREAD

**Issue by klitztuch** [zeropingheroes/lanager#94]
Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Maximum execution time of 30 seconds exceeded"

Stacktrace:
#1 Symfony\Component\Debug\Exception\FatalErrorException in /var/www/lanager/bootstrap/compiled.php:7298
#0 Illuminate\Exception\Handler:handleShutdown in <#unknown>:0

**Comment by ilumos** [comment]
Logs are pretty heavy going, especially when the table gets pretty big. Try deleting all but say 1,000 of the log entries and see if it still times out.

Also what spec server are you running out of interest?

**Comment by klitztuch** [comment]
There are not even 1.000 entries in the log files. Don't think it can be the size.

I'm running the server on a Raspberry Pi B+ with Raspbian

**Comment by cruelviper** [comment]
ok, than it is the memory, clean all the logs and leave 10 entries, it should work.

**Comment by ilumos** [comment]
Hi folks. The new version of LANager currently in development uses pagination so will not be so heavy when retreiving log entries.
