### ISSUE TITLE
translate french

### ISSUE THREAD

**Issue by juan-marco** [zeropingheroes/lanager#96]
I would like to translate the text in French :

the nav bar is nav.blade.php
I search the page file : events, users, games, info, extras and link

cordially

**Comment by juan-marco** [comment]
I well advanced but I do not find : 

-delete this shout
-the headline at the top of pages

-on events : day week and today
Ended and closed

-on users : in game

-on info : all pages

-on dashboard : the headline 

and add links


I translate everything else

**Comment by ilumos** [comment]
> delete this shout

Check the `lanager/app/lang/en` folder

> events tabs

You will need to implement internationalisation in the `lanager/public/vendor/fullcalendar` library - see http://fullcalendar.io/js/fullcalendar-2.5.0/demos/languages.html

> users in game

Check `lanager/app/Domain/States/StatePresenter.php`

> dashboard

Check `/lanager/app/views/dashboard/index.blade.php`

> adding links

Add them to `/lanager/app/config/lanager/links.php`

**Comment by juan-marco** [comment]
thank you for your help

-it remains for me to change the title as the top of pages like for example : Games Being Played, users, shouts ....

-the bottom of pages

-the title tab: LANager display in browsers

-and events tabs. I do not see how to change because the fullcalendar does not have the same structure

**Comment by juan-marco** [comment]
everything is now translated except the date and time. 

Fullcalendar does ont Have the same structure

**Comment by ilumos** [comment]
To translate the calendar library please follow the instructions in their documentation here:

http://fullcalendar.io/docs/text/lang/
